# generated by fastapi-codegen:
#   filename:  location.yaml
#   timestamp: 2025-10-16T11:53:10+00:00

from __future__ import annotations

import logging

from fastapi import FastAPI, Request
from location.location_dispatcher import LocationDispatcher

from .models import Location

dispatcher: LocationDispatcher
logger = logging.getLogger(__name__)


def initialize_location_dispatcher(new_dispatcher: LocationDispatcher) -> None:
    """Initialize the dispatcher."""
    global dispatcher  # noqa: PLW0603
    dispatcher = new_dispatcher


location = FastAPI(
    title="Location API",
    version="1.0.0",
    description="API to retrieve information about locations.",
)


@location.get('/locations/{location_id}', response_model=Location, status_code=200)
async def get_locations_location_id(request: Request, location_id: str) -> Location:
    """Get location by ID."""
    logger.info(f'[get] /locations/{location_id} {await request.body()}')
    return await dispatcher.get_locations_location_id(location_id)
