# generated by fastapi-codegen:
#   filename:  /home/laurent/personal-workspace/event-discovery/location/src/api/specifications/location.yaml
#   timestamp: 2025-10-16T11:53:10+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class Location(BaseModel):
    id: str = Field(..., description='Unique identifier of the location')
    name: str = Field(..., description='Name of the location')
    latitude: float = Field(..., description='Latitude of the location')
    longitude: float = Field(..., description='Longitude of the location')
