[project]
name = "event"
version = "0.1.0"
description = "Event definitions and extraction logic for event-discovery."
authors = [
    { name = "Laurent Cocault" }
]
readme = "README.md"
requires-python = "==3.12"
dependencies = [
    "fastapi",
    "fastapi-code-generator>=0.5.4",
    "pytest>=7.4.3",
    "pytest-asyncio>=0.26.0",
    "uv",
    "uvicorn"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
