[project]
name = "location"
version = "0.1.0"
description = "Location definitions and extraction logic for event-discovery."
authors = [
    { name = "Laurent Cocault" }
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi",
    "pytest>=7.4.3",
    "pytest-asyncio>=0.26.0",
    "uv",
    "uvicorn"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
markers = "asyncio: mark a test as asyncio-compatible"
