name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  build-and-test:
    name: Build and Test
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use locally installed Python 3.12
        run: |
          python3.12 --version
          python3.12 -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install .
        working-directory: ./location

      - name: Generate API (location)
        run: |
          . venv/bin/activate
          uv run src/api/generate_api.py
        working-directory: ./location

      - name: Run Python tests (location)
        env:
          PYTHONPATH: "src"
        run: |
          . venv/bin/activate
          pytest
        working-directory: ./location

      - name: Use locally installed Python 3.12
        run: |
          python3.12 --version
          python3.12 -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install .
        working-directory: ./event

      - name: Generate API (event)
        run: |
          . venv/bin/activate
          uv run src/api/generate_api.py
        working-directory: ./event

      - name: Run Python tests (event)
        env:
          PYTHONPATH: "src"
        run: |
          . venv/bin/activate
          pytest
        working-directory: ./event

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Node.js dependencies (wui)
        run: npm install
        working-directory: ./wui

      - name: Run JavaScript tests (wui)
        run: npm test
        working-directory: ./wui

  deploy:
    name: Deploy
    needs: build-and-test
    runs-on: self-hosted

    steps:

      - name: Deploy Server to VPS via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd event-discovery
            git pull
            cd event
            python3.12 -m venv venv
            . venv/bin/activate
            pip install .
            nohup ./run_event_server.sh > event.log 2>&1 &

      - name: Deploy WUI to VPS via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd event-discovery/wui
            git pull
            bun install
            nohup bun run start > wui.log 2>&1 &
